server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: docker
  docker_scrape:
    host: unix:///var/run/docker.sock
    json: true
    label_keys:
      - container_name
  relabel_configs:
    - source_labels: [__meta_docker_container_name]
      regex: /(.+)
      target_label: container
    - source_labels: []
      target_label: host
      replacement: docker-host  